# version: '3'
# バージョンは指定しなくていい使用になったらしい

services:
  db:
    image: mariadb
    build: ./requirements/mariadb
    container_name: "db"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - inceptionnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]

  wordpress:
    depends_on:
      # - db
      db:
        condition: service_healthy
    build: ./requirements/wordpress
    image: wordpress
    container_name: "wordpress"
    volumes:
      - ./requirements/wordpress/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - wordpress:/var/www/html
    restart: always
    networks:
      - inceptionnet #wordpressとnginが同じネットワークに所属するため

  nginx:
    build: ./requirements/nginx #nginxのDockerfileのpath
    image: nginx #作成するイメージ名
    container_name: "nginx"
    ports:
      - "80:80" #あとで消す
      - "443:443"
    restart: always #失敗した時に自動的に再起動
    volumes:
      - ./requirements/nginx/default:/etc/nginx/sites-available/default  #コンフィグファイルをコピー
      - wordpress:/var/www/html
    networks:
      - inceptionnet
    depends_on:
      - wordpress #wordpressが立ち上がってからnginxを立ち上げる

# nginxもwoedpressのファイルを参照できるようにする
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/takimotoshiho/data/v-wordpress/
  db_data:
    name: db_data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/takimotoshiho/data/v-db/


networks:
  inceptionnet:
    driver: bridge
