# version: '3'
# バージョンは指定しなくていい使用になったらしい

services:
  # db:
  #   image: mysql:8.3.0 # mysqlのバージョンは適宜変えてください
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: examplepassword
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: examplepassword

  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress:latest
  #   volumes:
  #     - ./wordpress:/var/www/html
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: examplepassword
  #     WORDPRESS_DB_NAME: wordpress
  #   ports:
  #     - "8000:80"

  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx"
    ports:
      - "8080:80" #あとで消す
      - "443:443"
    restart: always #失敗した時に自動的に再起動
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf  #コンフィグファイルをコピー
    # depends_on:
    #   - wordpress #wordpressが立ち上がってからnginxを立ち上げる


  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - wordpress

volumes:
  db_data:
